---
# Simulation initialization parameters.
initial_custom_flag: "True"
week_index: 0
demand_patterns_path: "Demand_patterns/three_year_demands_ctown.csv" # that file was this one. the total demand pattern csv
starting_demand_path: "Demand_patterns/starting_demand_points.csv" # that would be this file
initial_tank_levels_path: "Demand_patterns/tank_initial_conditions.csv" #

output_ground_truth_path: "physical_process.csv"
duration_days: 1
inp_file: "ctown_map.inp"
simulator: "pdd"
simulation_tpye: "Batch"
influxdb:
  host: "localhost"
  port: 8086
  username: ""
  password: ""
  database: "water2"
