# Digital Twin Configuration
# --------------------------

# Network Configuration
network:
  host: '127.0.0.1'
  scada_port: 5000
  result_port: 6000
  influx_port: 8086

# InfluxDB Configuration
influxdb:
  host: "192.168.11.105"
  port: 8086
  user: ''
  password: ''
  database: 'water2'

# Simulation Configuration
simulation:
  step_delay_sec: 60
  abs_tol: 0.002
  rel_tol: 0.1
  max_fail_ratio: 0.3
  start_from: 0
  max_steps: 48

# File Paths
paths:
  # Data files
  test_csv: "/mnt/data/home/zayd/Digital_twin_project/machine_learning/dataset/Ctown/test.csv"
  augmented_csv: "/mnt/data/home/zayd/Desktop/Digital_twin_project/machine_learning/dataset/Ctown/augmented_9_3_1.csv"
  junctions_data: "/mnt/data/home/zayd/Digital_twin_project/machine_learning/dataset/Ctown/junctions"
  inp_file: "/mnt/data/home/zayd/Digital_twin_project/inp_networks/ctown_map.inp"
  
  # Model files
  model_dir: "/mnt/data/home/zayd/Digital_twin_project/machine_learning/model_trained/LightGBM_0.1.0"
  feature_dict: "feature_and_target.json"
  logs_dir: "logs"

# Model Configuration
model:
  type: "lightgbm"
  format: ".txt"
  seq_length: 23
  feature_scaler_dir: "scalers"
  target_scaler_dir: "scalers"

# Mininet Topology
mininet:
  hosts:
    h1: {ip: '10.0.0.1/24', desc: 'SCADA'}
    h2: {ip: '10.0.0.2/24', desc: 'Simulation server'}
    h3: {ip: '10.0.0.3/24', desc: 'PLC1'}
    h4: {ip: '10.0.0.4/24', desc: 'PLC2'}
    h5: {ip: '10.0.0.5/24', desc: 'Visualization'}
  switch: s1
  bandwidth: 10
  delay: '5ms'

# Virtual Environment
venv:
  python_path: "/home/zayd/Desktop/Digital_twin_project/digitaltwin/bin/python"
